plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
}

Properties properties = new Properties()
if (rootProject.file("local.properties").exists()) {
    properties.load(rootProject.file("local.properties").newDataInputStream())
}

android {
    namespace 'com.vtstudio.fxbox'
    compileSdk 34

    defaultConfig {
        applicationId "com.vtstudio.fxbox"
        minSdk 28
        //noinspection ExpiredTargetSdkVersion
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }

        def keysStr = properties.getProperty("RAPID_API_KEYS", "")
        def formattedKeys = keysStr.isEmpty() ? "" : keysStr.split(",").collect { "\"${it.trim()}\"" }.join(", ")
        buildConfigField "String[]", "RAPID_API_KEYS", "new String[]{$formattedKeys}"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    // Kotlin và AndroidX Core
    implementation 'androidx.core:core-ktx:1.8.0'
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.0')
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.2'

    // Compose UI
    implementation 'androidx.activity:activity-compose:1.5.1'
    implementation platform('androidx.compose:compose-bom:2022.10.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'

    // Material Design
    implementation 'com.google.android.material:material:1.5.0'

    // AndroidX AppCompat và ConstraintLayout
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Android Navigation Components
    implementation 'androidx.navigation:navigation-fragment:2.6.0'
    implementation 'androidx.navigation:navigation-ui:2.6.0'

    //debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.12'

    // Các thư viện bên ngoài
     // Thư viện tải và hiển thị ảnh
    implementation 'com.squareup.okhttp3:okhttp:4.10.0' // Thư viện HTTP
    implementation 'androidx.media:media:1.7.0' // Hỗ trợ các tính năng liên quan đến Media
    implementation 'com.google.android.exoplayer:exoplayer:2.15.0' // Thư viện ExoPlayer cho phát truyền phương tiện
    implementation 'com.github.bosphere.android-fadingedgelayout:fadingedgelayout:1.0.0' // FadingEdgeLayout library
    implementation 'com.google.code.gson:gson:2.10.1' // Gson để xử lý JSON
    implementation 'org.jsoup:jsoup:1.14.3' // Jsoup để xử lý HTML
    implementation 'com.github.bumptech.glide:glide:4.15.1' // Glide để tải và hiển thị hình ảnh
    implementation 'io.github.glailton.expandabletextview:expandabletextview:1.0.4' // ExpandableTextView library

//    implementation 'at.blogc:expandabletextview:1.0.5'
    implementation 'com.airbnb.android:lottie:6.1.0'
    implementation 'net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent:3.0.0-RC3'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'com.tbuonomo:dotsindicator:5.0'
    implementation 'me.relex:circleindicator:2.1.6'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.github.tuanhav95:DragView:1.1.0'
    implementation 'com.github.TheHasnatBD:SweetToast:1.0.2'
    implementation 'com.saadahmedev.popup-dialog:popup-dialog:1.0.5'
    implementation 'com.github.sealedtx:java-youtube-downloader:3.2.6'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.github.Jay-Goo:RangeSeekBar:3.0.0'

    // implementation 'com.github.getActivity:EasyWindow:10.6'
   // implementation 'com.github.chrisbanes:PhotoView:2.3.0'
   // implementation 'io.github.imablanco:zoomy:1.0.0'
//    implementation platform('com.google.firebase:firebase-bom:32.7.0')
//    implementation 'com.google.firebase:firebase-analytics'
    //implementation 'com.github.iammert:ScalingLayout:1.2.1'
   // implementation 'com.facebook.fresco:fresco:3.1.3'
//    implementation group: 'org.apache.opennlp', name: 'opennlp-tools', version: '1.9.3'
   // debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.12'
    // room database
    def room_version = "2.5.0"
    //noinspection GradleDependency
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

}